[Desktop Entry]
Name=Mocha Dock
Name[ar]=رصيف لاتيه
Name[az]=Mocha Dok Paneli
Name[ca]=Acoblador Mocha
Name[ca@valencia]=Acoblador Mocha
Name[cs]=Dok Mocha
Name[da]=Mocha-dok
Name[de]=Mocha-Dock
Name[el]=Mocha Dock
Name[en_GB]=Mocha Dock
Name[eo]=Mocha Doko
Name[es]=Mocha Dock
Name[et]=Mocha dokk
Name[eu]=Mocha Dock
Name[fi]=Mocha-telakka
Name[fr]=Barre des tâches de Mocha
Name[gl]=Doca Mocha
Name[he]=מעגן לאטה
Name[hsb]=Mocha pas
Name[id]=Dock Mocha
Name[it]=Mocha Dock
Name[ko]=Mocha 독
Name[lt]=Mocha dokas
Name[nl]=Mocha Dock
Name[nn]=Mocha-dokk
Name[pl]=Dok Mocha
Name[pt]=Área Acoplável do Mocha
Name[pt_BR]=Mocha Dock
Name[ru]=Mocha Dock
Name[sk]=Dok Mocha
Name[sl]=Mocha Dock
Name[sv]=Mocha dockningsfönster
Name[tr]=Mocha Rıhtım
Name[uk]=Панель Латте
Name[zh_CN]=Mocha 停靠栏
Name[zh_TW]=Mocha Dock
Comment=Dock for the masses
Comment[ar]=رصيف للأمور الكبيرة
Comment[az]=Hər kəs üçün Dok panel
Comment[ca]=Acoblador per a les masses
Comment[ca@valencia]=Acoblador per a les masses
Comment[cs]=Dok pro masy
Comment[da]=Dok til masserene
Comment[de]=Dock für die Massen
Comment[el]=Διαχειριστής εργασιών για όλον τον κόσμο
Comment[en_GB]=Dock for the masses
Comment[eo]=Doko por la masoj
Comment[es]=Un dock para las masas
Comment[et]=Dokk massidele
Comment[eu]=Jendartearen kaia
Comment[fi]=Telakka massoille
Comment[fr]=Une barre des tâches pour tout le monde
Comment[gl]=Doca para as masas.
Comment[he]=מעגן להמונים
Comment[hsb]=Pas za wšěch
Comment[id]=Dock untuk mengumpulkan
Comment[it]=Area di aggancio per le masse
Comment[ja]=人々のためのドック
Comment[ko]=모두를 위한 독
Comment[lt]=Dokas masėms
Comment[nl]=Dock voor de massa
Comment[nn]=Dokk for massane
Comment[pl]=Dok dla mas
Comment[pt]=Área acoplável para as massas
Comment[pt_BR]=Área acoplável para todos
Comment[ru]=Док для всех
Comment[sk]=Dok pre davy ľudí
Comment[sl]=Dok za množice
Comment[sv]=Dockningsfönster för alla
Comment[tr]=Kitleler için rıhtım
Comment[uk]=Панель для усіх
Comment[zh_CN]=给大众使用的停靠栏
Comment[zh_TW]=給大眾使用的 Dock
GenericName=Dock
GenericName[ar]=مرسى
GenericName[az]=Dok
GenericName[ca]=Acobla
GenericName[ca@valencia]=Acobla
GenericName[cs]=Dok
GenericName[da]=Dok
GenericName[de]=Dock
GenericName[el]=Dock
GenericName[en_GB]=Dock
GenericName[eo]=Doko
GenericName[es]=Dock
GenericName[et]=Dokk
GenericName[eu]=Kaia
GenericName[fi]=Telakka
GenericName[fr]=Barre des tâches
GenericName[gl]=Doca
GenericName[he]=מעגן 
GenericName[hsb]=Pas
GenericName[ia]=Bassino
GenericName[id]=Dok
GenericName[it]=Aggancio
GenericName[ja]=ドック
GenericName[ka]=მიმაგრება
GenericName[ko]=독
GenericName[lt]=Dokas
GenericName[nl]=Dock
GenericName[nn]=Dokk
GenericName[pl]=Dok
GenericName[pt]=Área Acoplável
GenericName[pt_BR]=Área acoplável
GenericName[ru]=Док
GenericName[sk]=Dok
GenericName[sl]=Dok
GenericName[sv]=Dockningsfönster
GenericName[tr]=Rıhtım
GenericName[uk]=Панель
GenericName[zh_CN]=停靠栏
GenericName[zh_TW]=Dock
Icon=mocha-dock
Categories=Utility;X-SuSE-DesktopUtility;
Exec=@CMAKE_INSTALL_PREFIX@/bin/mocha-dock
InitialPreference=1
StartupNotify=false
Terminal=false
Type=Application
StartupWMClass=mocha-dock
X-DBUS-ServiceName=org.kde.mochadock
X-DBUS-StartupType=unique
X-KDE-PluginInfo-Author=@AUTHOR@
X-KDE-PluginInfo-Email=@EMAIL@
X-KDE-PluginInfo-Version=@VERSION@
X-KDE-PluginInfo-Website=@WEBSITE@
X-KDE-StartupNotify=false
X-KDE-SubstituteUID=false
X-KDE-Wayland-Interfaces=org_kde_plasma_window_management,org_kde_kwin_keystate,zkde_screencast_unstable_v1

